name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: teogale
        uses: docker/login-action@v1 
        with:
          username: teogale
          password: ${{ secrets.%SECRET_DOCKER_TOKEN% }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: teogale/testnginx:latest
